README.md

in my opinion using the Libraries folder is better than creating a Plugins folder because
1. the folder already exists so one less step 
2. will show in the list of loadable plugins for the launcher

change from recommending creating a Plugins folder to recommending using the already existing Libraries folder

---

NeosModLoader/NeosModLoader.csproj
NeosModLoader/packages.config
README.md

Cleans up the csproj file to a standard format that enables at least building on Unix systems with the path resolves with a default to a local folder that can be symlinked instead of hard coded windows paths. Additionally moves the Harmony nuget package to just be a PackageReference.

Csproj cleanup, unix buildable

---

.github/CONTRIBUTING.md
NeosModLoader/NeosModLoader.csproj
README.md
doc/config.md
doc/directories.md
doc/faq.md
doc/how_nml_works.md
doc/linux.md
doc/making_mods.md
doc/modloader_config.md
doc/neos_guidelines.md
doc/neos_standalone_setup.md
doc/problem_solving_techniques.md
doc/troubleshooting.md

Whilst investigating a separate possible NML addition, I noticed quite a few minor problems and thought I'd fix them first;
- Updated harmony version
- Changed csproj old "Plugins" build option to "Libraries"
- Markdown files are consistently missing newlines
- usually it's considered best practice to have headings, code blocks and lists surrounded by new lines
- Also only having a single h1 level heading
- Added linux paths to docs
- Other misc changes, mostly removing extra spaces and normalizing tabs to spaces, and fixing numbered list numbers

Misc cleanup

---

NeosModLoader/ModConfigurationDefinitionBuilder.cs
NeosModLoader/ModLoader.cs

Removes the very verbose configuration logging, and cleans up logging of loading mods.
The log messages would now happen as after mods are actually loaded by NML instead of when the hooks for a mod are going to be ran.
Example log section when loading mods:
```log
...
15:29:16.901 (  0 FPS)  [INFO] [NeosModLoader] loading mods from /home/lj/.local/share/Steam/steamapps/common/NeosVR/nml_mods
15:29:16.907 (  0 FPS)  [INFO] [NeosModLoader] loaded mod [ContactsPublishedWorldsButton/1.0.0] (ContactsPublishedWorldsButton.dll) by badhaloninja
15:29:16.911 (  0 FPS)  [INFO] [NeosModLoader] loaded mod [Dark Mode LogiX Browser/1.0.4] (DarkLogiXBrowser.dll) by Cyro
15:29:16.915 (  0 FPS)  [INFO] [NeosModLoader] loaded mod [GetItemLink/1.1.0] (GetItemLink.dll) by eia485
15:29:16.915 (  0 FPS) …
```

Make mod loading logging a bit cleaner

---

NeosModLoader/JsonConverters/EnumConverter.cs
NeosModLoader/JsonConverters/NeosPrimitiveConverter.cs
NeosModLoader/ModConfiguration.cs
NeosModLoader/ModLoader.cs
NeosModLoader/Properties/AssemblyInfo.cs
NeosModLoader/SplashChanger.cs

This allows existing pre-1.9 configs with enums to be deserialized gracefully, while all new saved enums will turn into strings from this point on.

Fix for 1.9.0 Enum handling

---

NeosModLoader/ModConfiguration.cs

There are two usages of the obsolete method NeosMod.GetConfigurationDefinition()
1. The usage in ModConfiguration.LoadConfigForMod() is correct and necessary
2. The usage in ModConfiguration.Save() was redundant and unnecessary

Document intentional call to obsolete method

---

README.md
doc/linux.md
doc/modloader_config.md

Changes the Harmony link to a more up to date one, the license links to just the master branch ones instead of specific ones, and also additionally makes some docs slightly clearer.

Some very minor markdown cleanup

---

NeosModLoader/ModConfiguration.cs

This is to add better logging for a common failure case where a specific key is failing to load, for example if someone changed the key's type across mod versions.

More specific logging if a config key fails to load

---

NeosModLoader/AssemblyLoader.cs
NeosModLoader/DebugInfo.cs
NeosModLoader/JsonConverters/EnumConverter.cs
NeosModLoader/Logger.cs
NeosModLoader/ModConfiguration.cs
NeosModLoader/ModLoader.cs
NeosModLoader/NeosMod.cs
NeosModLoader/NeosVersionReset.cs

- Adds the ability for mods to only build debug log strings if debug logging is enabled via new public API:
- DebugFunc()
- IsDebugEnabled()
Originally part of #38, but I've separated the two

debug log changes

---

NeosModLoader/ModConfiguration.cs
NeosModLoader/Utility/EnumerableInjector.cs

This is based on a gist from the Harmony creator.
It's useful for patching methods that return `IEnumerable<>` or `IEnumerator<>` .
For example:
* https://github.com/Banane9/NeosAvatarClothingHelper/blob/master/AvatarClothingHelper/AvatarClothingHelper.cs#L86
* https://github.com/Banane9/NeosEditorTabbing/blob/master/EditorTabbing/EditorTabbing.cs#L82
There may be more utilities coming if you think this is a good fit.

Add Utility Enumerable Injector

---

NeosModLoader/ModLoader.cs
NeosModLoader/Utility/EnumerableInjector.cs

This is to help troubleshoot mod loading issues such as [this](https://discord.com/channels/901126079857692714/901129369832026213/992713735514882089).
Relevant log snippet:
```
8:42:44 pm.573	[ERROR][NeosModLoader] Unexpected exception initializing mod from C:\Program Files (x86)\Steam\steamapps\common\NeosVR\HeadlessClient\nml_mods\HeadlessTweaks.dll:
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
at System.Reflection.Assembly.GetTypes()
at NeosModLoader.ModLoader.InitializeMod(AssemblyFile mod)
at NeosModLoader.ModLoader.LoadMods()
```
I'm actually very mad that Microsoft just logs in their Exception.ToString() …

Additional logging for ReflectionTypeLoadException

---

NeosModLoader/ExecutionHook.cs
NeosModLoader/ModLoader.cs
NeosModLoader/NeosModLoader.csproj

1. AssemblyName is now ALWAYS NeosModLoader, because apparently Windows requires this?
2. Adds some extra logging for what nml_libs get loaded

Unbork AssemblyName on headless build

---

NeosModLoader/ModLoader.cs
NeosModLoader/Properties/AssemblyInfo.cs

1. PostX does nothing beneficial to NML, and is not needed
2. PostX changes NML's hash, which could be potentially problematic
- If we ever sign the DLL
- If the mod manager verifies files
3. PostX changes NML's AssemblyVersionAttribute, which can lead to extremely confusing logs
Specifically, logs like this are confusing because there is no such thing as NML version 2022.4.24.539
```
Loader Exception: Could not load file or assembly 'NeosModLoader, Version=2022.4.24.539, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
```

Prevent PostX processing of the NML assembly

---

doc/modloader_config.md

the current description could confuse users into thinking that this config option would also hide any mode created visuals. if nml ever gets anymore direct visuals (unlikely) we can update the docs.

clearify hidevisuals config option

---

NeosModLoader/AssemblyFile.cs
NeosModLoader/AssemblyLoader.cs
NeosModLoader/NeosModLoader.csproj

This PR makes the modloader also search subdirectories of nml_mods when loading mods.
Additionally it prevents a mod from being loaded twice if it is appears twice in nml_mods.
Motivations:
1. This lets people organize their nml_mods folder a bit more.
2. This lets people dump a bunch of mods into a folder and distribute it as a modpack that others can just drop into nml_mods

Recursive loading of mods from nml_mods

---

doc/how_nml_works.md

sls asked for this https://discord.com/channels/901126079857692714/901129181453230130/1003774038675574845

Document the other ways NML touches neos

---

.editorconfig
.github/workflows/test.yml
NeosModLoader.sln
NeosModLoader/AssemblyFile.cs
NeosModLoader/AssemblyLoader.cs
NeosModLoader/AutoRegisterConfigKeyAttribute.cs
NeosModLoader/ConfigurationChangedEvent.cs
NeosModLoader/DebugInfo.cs
NeosModLoader/DelegateExtensions.cs
NeosModLoader/ExecutionHook.cs
NeosModLoader/JsonConverters/EnumConverter.cs
NeosModLoader/JsonConverters/NeosPrimitiveConverter.cs
NeosModLoader/LoadedNeosMod.cs
NeosModLoader/Logger.cs
NeosModLoader/ModConfiguration.cs
NeosModLoader/ModConfigurationDefinitionBuilder.cs
NeosModLoader/ModConfigurationKey.cs
NeosModLoader/ModLoader.cs
NeosModLoader/ModLoaderConfiguration.cs
NeosModLoader/NeosMod.cs
NeosModLoader/NeosModBase.cs
NeosModLoader/NeosVersionReset.cs
NeosModLoader/SplashChanger.cs
NeosModLoader/Util.cs
NeosModLoader/Utility/EnumerableInjector.cs

Fixes CI hopefully.
I recommend reviewing with whitespace hidden.

Propper unified formatting

---

.editorconfig
.github/CONTRIBUTING.md
NeosModLoader.sln
NeosModLoader/AssemblyFile.cs
NeosModLoader/AssemblyLoader.cs
NeosModLoader/AutoRegisterConfigKeyAttribute.cs
NeosModLoader/ConfigurationChangedEvent.cs
NeosModLoader/DebugInfo.cs
NeosModLoader/DelegateExtensions.cs
NeosModLoader/ExecutionHook.cs
NeosModLoader/JsonConverters/EnumConverter.cs
NeosModLoader/JsonConverters/NeosPrimitiveConverter.cs
NeosModLoader/LoadedNeosMod.cs
NeosModLoader/Logger.cs
NeosModLoader/ModConfiguration.cs
NeosModLoader/ModConfigurationDefinitionBuilder.cs
NeosModLoader/ModConfigurationKey.cs
NeosModLoader/ModLoader.cs
NeosModLoader/ModLoaderConfiguration.cs
NeosModLoader/NeosMod.cs
NeosModLoader/NeosModBase.cs
NeosModLoader/NeosModLoader.csproj
NeosModLoader/NeosVersionReset.cs
NeosModLoader/SplashChanger.cs
NeosModLoader/Util.cs
NeosModLoader/Utility/EnumerableInjector.cs

Changes everything to tabs. Removes human-readable whitespace guidelines from CONTRIBUTING.md as they are superseded by editorconfig.
`dotnet format` doesn't run on csproj or sln files so I've formatted them manually.
**THE PRS WILL CONTINUE**  
**UNTIL MORALE IMPROVES**

What if we used tabs, though?

---

doc/faq.md

Adding note regarding whether NML is detectable by other users

Disclaimer about detectability

---

doc/faq.md

I've seen many users asking recently if mods are safe are not, and I think it's worth adding to the FAQ on this topic that we have the manually audited list.

Add reference to mod list in the "Are mods safe?" FAQ

---

NeosModLoader/ModLoader.cs
NeosModLoader/NeosVersionReset.cs
NeosModLoader/Util.cs

Resolves #58.
This enumerates all loaded assemblies and uses a couple of heuristics to make a *very* educated guess about which ones are plugins. Those plugins are then used in the compatibility hash calculation.
---
edit: I'll go into more detail
1. Enumerate all loaded assemblies using Froox's own `[module: Description("POSTX_PROCESSED")]` marker to filter to just the PostX processed assemblies
2. Attempt to correlate the PostX'd assemblies with Neos's `Engine.ExtraAssemblies`. ExtraAssemblies is a list of the loaded plugins, but it only contains their filenames. No path information.
3. Do some set theory to check for assemblies we couldn't match to plugins and plugins we couldn't match to assemblies.
- assemblies we couldn't match to plugins aren't a huge deal, and we actually expect a …

Fix compatibility hash spoofing when plugins are present.

---

NeosModLoader/AssemblyLoader.cs

This fixes #53.
I don't know why. I don't know how. Send help.
Look at these docs. Nothing in them has a big ol "danger this will just be broken in some cases" label. WTF.  
[Assembly.LoadFrom](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.loadfrom?view=net-6.0)  
[Assembly.LoadFile](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.loadfile?view=net-6.0)

Fix assembly loading on windows headless

---

NeosModLoader/ModConfiguration.cs
NeosModLoader/Util.cs

SectOLT back with another fun bug:
```log
Restoring currently updating root. Stack:
at void FrooxEngine.UpdateManager.RestoreRootCurrentlyUpdating() in C:/Sync/Projects/Software/Applications/NeoS/NeosFramework/FrooxEngine/Data%20Model/Controllers/UpdateManager.cs:line 141
at bool FrooxEngine.UpdateManager.RunUpdates() in C:/Sync/Projects/Software/Applications/NeoS/NeosFramework/FrooxEngine/Data%20Model/Controllers/UpdateManager.cs:line 470
at bool FrooxEngine.World.RefreshStep() in C:/Sync/Projects/Software/Applications/NeoS/NeosFramework/FrooxEngine/World.cs:line 1588
at bool FrooxEngine.World.Refresh() in C:/Sync/Projects/Software/Applications/NeoS/NeosFramework/FrooxEngine/World.cs:line 1257
at void FrooxEngine.WorldManager.UpdateStep(double maxMilliseconds) in …
```

Attempt to fix a config autosave NRE

---

NeosModLoader/ModConfiguration.cs
NeosModLoader/ModConfigurationKey.cs
NeosModLoader/Util.cs

Fix Nullable<T> configs

---

NeosModLoader/AssemblyHider.cs
NeosModLoader/ModLoader.cs
NeosModLoader/Util.cs

Short story: this fixes https://github.com/New-Project-Final-Final-WIP/HeadlessTweaks/issues/4.
Long story: It turns out some mods have types that cannot be loaded at runtime, because assemblies they depend on are in turn not loaded. .NET *really* doesn't like if you try to inspect those types with reflection, which both NML and Neos try to do. Two things were done to fix this:
1. ModLoader.cs now loads types through an alternate, safer mechanism (that's an evil hack involving slinging a bunch of exceptions around)
2. If Neos tries to call `AppDomain.CurrentDomain.GetAssemblies()` we intercept that and filter out mod assemblies
With these fixes in place I've confirmed that HeadlessTweaks no longer crashes on Windows headless.

Allow loading of mods with unloadable types

---

NeosModLoader/Util.cs

This bug caused all mods with more than one type that also lack any unloadable types to fail to load.

Fix a bug in GetLoadableTypes

---

NeosModLoader/Util.cs

It turns out that this wasn't needed, and in fact it causes problems as NeosMod implementations don't actually *need* a TypeInitializer. This code was preventing certain mods from loading.

Remove typeinitializer check

---

NeosModLoader/ModConfiguration.cs

The original mod configuration implementation saved synchronously, but in #38 *all* config saving was switched over to a background thread. While doing some unrelated debugging I noticed that the shutdown hook saves were also asynchronous, and it struck me as incorrect and dangerous.
It's pretty typical for 10s of mods to save configs on shutdown, and I don't think there's a compelling performance benefit to doing all that IO concurrently. However, I *do* think there's a compelling safety benefit to doing all the saves synchronously: I believe Task.Run() uses background threads, which do not keep the managed execution environment running. In other words, there's no guarantee those background saves won't get interrupted. Doing the saves synchronously ensures they'll actually finish before …

Save configs synchronously on shutdown

---

NeosModLoader/AssemblyHider.cs
NeosModLoader/Logger.cs
NeosModLoader/ModConfiguration.cs
NeosModLoader/NeosVersionReset.cs
NeosModLoader/Util.cs

This does the following:
- Minor logging cleanup
- Capture stack traces at top level vs doing frame-skipping arithmetic. I think this is actually mandatory as I was seeing some strange logging behavior on Windows Headless that I can only explain if .NET was inlining method calls, which obviously would ruin my "skip 4 frames" style of arithmetic.
- Stop intercepting internal .NET calls to `AppDomain.GetAssemblies()`. It turns out that .NET calls this a lot internally, and my logic that was *supposed* to be intercepting FrooxEngine calls was also messing with internal .NET calls not initiated by FrooxEngine. I've implemented a smarter stack frame search to solve this.

Various Logging Fixes

---

NeosModLoader/AssemblyLoader.cs

Hi @Banane9, this is for you.
This fixes a bug where NML would load files like "foo.dll_disabled" because Microsoft's APIs are trash.

Fix the garbage that Directory.GetFiles returns

---

NeosModLoader/IgnoresAccessChecksToAttribute.cs

Adding this to be able to properly mark mods using publicized assemblies while building, in case Neos ever moves off Mono or they change their behavior.

Adds IgnoresAccessChecksToAttribute
